version: "3.8"
services:
  # Dedicated Postgres container for Airflow metadata
  postgres:
    image: postgres:13
    container_name: airflow-metadata-db
    environment:
      POSTGRES_DB: airflow_meta
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - job-market-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Airflow service
  airflow:
    image: apache/airflow:2.8.3
    container_name: job-market-airflow
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_meta
      AIRFLOW__CORE__FERNET_KEY: "" # Generate one with: fernet_key = Fernet.generate_key()
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      # Project-specific variables
      ADZUNA_APP_ID: ${ADZUNA_APP_ID}
      ADZUNA_APP_KEY: ${ADZUNA_APP_KEY}
      PYTHONPATH: /opt/airflow
    volumes:
      - ./project:/opt/airflow/project
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - .:/opt/airflow
      - ./requirements.txt:/opt/airflow/requirements.txt
    ports:
      - 8080:8080
    networks:
      - job-market-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: >
      bash -c "
      pip install --no-cache-dir -r /opt/airflow/requirements.txt &&
      airflow db init &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
      (airflow scheduler &) &&
      airflow webserver
      "
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  streamlit:
    image: python
    container_name: job-market-dashboard
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8501:8501
    networks:
      - job-market-network
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
      pip install streamlit pandas sqlalchemy psycopg2-binary plotly python-dotenv &&
      streamlit run dashboard.py --server.address=0.0.0.0
      "

networks:
  job-market-network:
    driver: bridge

volumes:
  postgres_data:
