services:
  postgres:
    image: postgres:latest
    container_name: job-market-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5430:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - job-market-network

volumes:
  postgres_data:

networks:
  job-market-network:
